UlysseCarpentier/GHActions-Git-Brother:
####################
# GitHub Actions Help
####################
  - source: ./GitHubActionsHelp/R_GitHub.yml
    dest: .github/workflows/R_GitHub.yml


####################
# Slack
####################
  - source: ./Slack/R_Slack_Notification.yml
    dest: .github/workflows/R_Slack_Notification.yml
