UlysseCarpentier/GHActions-Git-Brother:
  - source: ./Python/R_GHA_Build.yml
    dest: .github/workflows/R_GHA_Build.yml

  - source: ./Python/R_action.yml
    dest: .github/workflows/R_action.yml

  - source: ./Archive/R_Archive_Reusable.yml
    dest: .github/workflows/R_Archive_Reusable.yml

  - source: ./Archive/R_Notify.yml
    dest: .github/workflows/R_Notify.yml
