UlysseCarpentier/GHActions-Git-Brother:
####################
# GitHub Actions Help
####################
  - source: ./GitHubActionsHelp/R_GitHub_GetSlackID.yml
    dest: .github/workflows/R_GitHub_GetSlackID_temp.yml

####################
# Slack
####################
  - source: ./Slack/R_Slack_Notification.yml
    dest: .github/workflows/R_Slack_Notification_temp.yml
