name: slack notification
name: Gradle config
on:
  workflow_call:
    inputs:
      slack_username:
        required: true
        type: string
      slack_message:
        required: true
        type: string
      slack_webhook:
        required: true
        type: string
      slack_title:
        required: true
        type: string
      slack_color:
        required: true
        type: string

jobs:
  notify-slack:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Slack notification job
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: ${{ inputs.slack_username }}
          SLACK_COLOR: ${{ inputs.slack_color }}
          SLACK_MESSAGE: ${{ inputs.slack_message }}
          SLACK_TITLE: ${{ inputs.slack_title}}
          # get the webhook_url from slack api when creating the incoming webhook
          SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
