name: Get Slack ID From GitHub Bio
on:
  workflow_dispatch:

#Rewrite as reusable???



jobs:
# Use this snippet in another workflow file to get Slack ID From GitHub Bio
  get_slack_id:
    name: Get GitHub Bio
    runs-on: ubuntu-latest
    outputs:
        bio: ${{ steps.get_slack_id.outputs.bio }}
    steps:
    - name: Get user github bio
      id: get_github_bio
      uses: actions/github-script@v7
      with:
        script: |
          const bio = await github.rest.users.getByUsername({
                username: context.actor
            }).then((response) => {
                console.log(response.data.bio)
                return response.data.bio
            })
          return bio
    - name : Get Slack ID from bio
      id: get_slack_id
      run: |
        slack_id=$(echo "${{steps.get_github_bio.outputs.result}}" | grep -oE 'U[0-9A-Z]+')
        echo "bio=$slack_id" >> $GITHUB_OUTPUT
    - name: Echo Slack ID
      run: |
        echo "${{steps.get_slack_id.outputs.bio}}"

# Use this snippet in another workflow file to get the output
  get_slack_id_output:
    name: Get Slack ID From GitHub Bio
    runs-on: ubuntu-latest
    needs: get_slack_id
    steps:
    - name: Echo Slack ID
      run: |
        echo "${{needs.get_slack_id.outputs.bio}}"
            

