name: slack notification
author: Ulysse Carpentier <ulysse@live.io>
description: |+
 Slack notification to your channel or person if you have his slack ID
on:
  workflow_call:
    inputs:
      slack_username:
        description: |+
          Slack username to send to
        required: true
        type: string
        default: test_bot
      slack_message:
        description: |+
          The message to send, formatted etc...
        required: true
        type: string
        default: README.md
jobs:
  notify-slack:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Slack notification job
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: ${{ inputs.slack_username }}
          SLACK_MESSAGE: ${{ inputs.slack_message }}
          # get the webhook_url from slack api when creating the incoming webhook
runs:
  using: "node20"
  main: "./dist/index.js"
