name: Get Slack ID
author: Ulysse Carpentier <ulysse.carpentier@ext-energy-pool.eu>
description: Get Slack ID from GitHub Bio.
on:
  workflow_call:
    outputs:
      slack_id:
        description: Slack ID
        value: ${{ jobs.get_slack_id.outputs.bio }}
      status:
        description: Status of the called job
        value: ${{ jobs.get_slack_id.outputs.status }}
jobs:
  get_slack_id:
    name: Get GitHub Bio
    runs-on: ubuntu-latest
    outputs:
      bio: ${{ steps.get_slack_id.outputs.bio }}
      status: ${{ job.status }}
    steps:
      - name: Get user github bio
        id: get_github_bio
        uses: actions/github-script@v7
        with:
          script: |
            const bio = await github.rest.users.getByUsername({
                  username: context.actor
              }).then((response) => {
                  console.log(response.data.bio)
                  return response.data.bio
              })
            return bio
      - name: Get Slack ID from bio
        id: get_slack_id
        run: |
          slack_id=$(echo "${{steps.get_github_bio.outputs.result}}" | grep -oE 'U[0-9A-Z]+')
          echo "bio=$slack_id" >> $GITHUB_OUTPUT
      - name: Echo Slack ID
        run: |
          echo "${{steps.get_slack_id.outputs.bio}}"
