name: From .txt to Matrix
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: dataStep
        run: |
          json_array=$(echo "{ \"target\": " $(< yaml_files.txt tr -d '\r' | jq -R . | jq -s . | jq -c .) " }")
          echo $json_array
          echo "matrix=$json_array" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.dataStep.outputs.matrix  }}

  run-matrix:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ${{fromJSON(needs.setup.outputs.matrix).target}}
    steps:
      - run: echo "${{matrix.target}}"
