name: Find Actions
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Need the repo checked out in order to read the file
      - uses: actions/checkout@v3
      - id: dataStep
        run: |
          json_array=$(echo "{ \"target\": " $(< yaml_files.txt tr -d '\r' | jq -R . | jq -s . | jq -c .) " }")
          echo $json_array
          echo "myoutput=$json_array" >> $GITHUB_OUTPUT
    outputs:
      mymatrix: ${{ toJSON(steps.dataStep.outputs.myoutput) }}

  run-matrix:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{needs.setup.outputs.mymatrix}}"
      - run: echo "${{fromJSON(needs.setup.outputs.mymatrix)}}"
      - run: echo "${{needs.setup.outputs.mymatrix.target}}"
      - run: echo "${{needs.setup.outputs.mymatrix.myoutput}}"
      - run: echo "${{needs.setup.outputs.mymatrix.myoutput}}"
