name: Find Actions
on:
  workflow_dispatch:
jobs:
  matrix-prep:
    # Prepares the 'bazelversion' axis of the test matrix
    runs-on: ubuntu-latest
    steps:
      # Need the repo checked out in order to read the file
      - uses: actions/checkout@v3
      - name: Read and process files
        run: |
          files=()
          while IFS= read -r line; do
            files+=("$line")
          done < yaml_files.txt
          json_array=$(echo "${files[@]}" | jq -R -s -c 'split("\n")[:-1]')
          echo "file_outputs=$json_array" >> $GITHUB_OUTPUT
        shell: bash
      - name: Display the output
        run: |
          echo "oui output: $GITHUB_OUTPUT"
        shell: bash
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs:
      - matrix-prep
    strategy:
      fail-fast: false
      matrix:
        yaml_file: ${{ fromJSON(needs.matrix-prep.outputs.file_outputs) }}
        readme_file: ${{ fromJSON(needs.matrix-prep.outputs.file_outputs) }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run github-action-readme-generator
        uses: bitflight-devops/github-action-readme-generator@v1.4.0
        with:
          action: ${{ matrix.yaml_file }}
