name: Find Actions
on:
  workflow_dispatch:
jobs:
  setup:
    # Prepares the 'bazelversion' axis of the test matrix
    runs-on: ubuntu-latest
    outputs:
      mymatrix: ${{ toJSON(steps.dataStep.outputs.myoutput) }}
    steps:
      # Need the repo checked out in order to read the file
      - uses: actions/checkout@v3
      - id: dataStep
        run: |
          json_array=$(jq -sR 'split("\n")[:-1]' yaml_files.txt)
          echo $json_array
          echo "myoutput=$json_array" >> $GITHUB_OUTPUT
  run-matrix:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.mymatrix) }}
    steps:
      - run: echo "helo"