name: Find Actions
on:
  workflow_dispatch:
jobs:
  path_file_init:
    # Prepares the 'bazelversion' axis of the test matrix
    runs-on: ubuntu-latest
    steps:
      # Need the repo checked out in order to read the file
      - uses: actions/checkout@v3
      - name: List YAML Files
        id: list-yaml-files
        run: |
          find . -type f -name '*.yml' -print > yaml_files.txt
          while IFS= read -r line; do echo "files=$line" >> $GITHUB_OUTPUT; done < yaml_files.txt
      - name: Print results
        run: |
          echo "${{ toJSON(steps.*.outputs.files) }}"
    outputs:
      files: ${{ toJSON(steps.list-yaml-files.outputs.files) }}
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "docs(readme): update README.md tables on ${{ github.ref_name }}"
          commit-message: "docs(readme): updated README.md inputs table"
          body: "Updated README.md inputs/outputs tables, according to action.yml file"
          branch: update-readme--${{ github.ref_name }}
          delete-branch: false
          labels: bot,documentation
      - name: Cleanup
        run: |
          rm -f matrix_input.yml
          rm -f yaml_files.txt