name: Find Actions
on:
  push:
  workflow_dispatch:
jobs:
  path_file_init:
    # Prepares the 'bazelversion' axis of the test matrix
    runs-on: ubuntu-latest
    steps:
      # Need the repo checked out in order to read the file
      - uses: actions/checkout@v3
      - name: List YAML Files
        id: list-yaml-files
        run: |
          find . -type f -name '*.yml' -print > yaml_files.txt
          while IFS= read -r line; do echo "files=$line" >> $GITHUB_OUTPUT; done < yaml_files.txt
      - name: Print results
        run: |
          echo "${{ toJSON(steps.*.outputs.files) }}"
    outputs:
      files: ${{ toJSON(steps.list-yaml-files.outputs.files) }}