name: Find Actions
on:
  workflow_dispatch:
jobs:
  matrix-prep:
    # Prepares the 'bazelversion' axis of the test matrix
    runs-on: ubuntu-latest
    steps:
      # Need the repo checked out in order to read the file
      - uses: actions/checkout@v3
      - name: List YAML Files
        id: list-yaml-files
        run: |
          find Python -type f -name '*.yml' -print > yaml_files.txt
          echo "::set-output name=paths::$(cat yaml_files.txt)"  
          while IFS= read -r line; do echo "file_output=$line" >> $GITHUB_OUTPUT; done < yaml_files.txt
    outputs:
      # Will look like '["6.0.0rc1", "5.3.2"]'
      files: ${{ toJSON(steps.*.outputs.file_output) }}