name: Notify
run-name: ${{ github.actor }} Testing name branch on create
on:
  create:
    branches:
      - '*'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install jq -y
      - name: Get GitHub Bio
        id: get_github_bio
        run: |
          id_git=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/users/${{ github.actor }} \
          | jq -r '.bio'); \
          echo "bio is $id_git"
          echo "bio=$id_git" >> $GITHUB_OUTPUT
      - name: Access id_git in Another Run
        run: |
          echo "The value of id_git from a previous run is: ${{ steps.get_github_bio.outputs.bio }}"
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          mention_users: ${{ github.workflow_run.outputs.id_git }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}