name: Readme Generator
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: output_matrix
        run: |
          yaml_files=$(find . -type f -name '*.yml' -not -path './.github/*' -exec sh -c 'echo "$(dirname "$1")/$(basename -s .yml "$1")"' _ {} \;)
          echo $yaml_files
          yaml_array=$(echo "$yaml_files" | jq -R -s 'split("\n")[:-1] | map(split(" ")) | flatten')
          quoted_array=$(echo "$yaml_array" | jq -c 'map("\"" + . + "\"")')
          target_string='{ "target":'
          end_string=' }'
          json_array="${target_string} ${yaml_array} ${end_string}"
          echo 'matrix='$json_array >> $GITHUB_OUTPUT
    outputs:
      actions: ${{steps.output_matrix.outputs.matrix}}

  run-matrix:
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      filename: ${{steps.name_action.outputs.filename}}
      match: ${{steps.check_file.outputs.match}}
    strategy:
      matrix:
       target: ${{fromJSON(needs.setup.outputs.actions).target}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Action name
        id: name_action
        run: |
          filename=$(basename "${{ matrix.target }}")
          echo "Filename is: $filename"
          echo 'filename='$filename >> $GITHUB_OUTPUT

      - name: Check if file exists
        id: check_file
        run: |
          if [ -e "${{ matrix.target }}".md ]; then
            echo "File exists!"
            echo "match=true" >> $GITHUB_OUTPUT
          else
            echo "File does not exist."
            cp "./Ressources/Base_README.md" "${{matrix.target}}".md
            echo "copied"
            echo "match=false" >> $GITHUB_OUTPUT
          fi
          

      - name: Run github-action-readme-generator
        id: doc_generator
        if: steps.check_file.outcome == 'success'
        uses: bitflight-devops/github-action-readme-generator@v1.4.0
        with:
          action: ${{ matrix.target }}.yml
          readme: ${{ matrix.target }}.md
      - name: Get Description
        id: get_desc
        if: steps.doc_generator.outcome == 'success' && ${{steps.check_file.outputs.match}} == 'true'
        run: |
          start_pattern='<!-- start description -->'
          end_pattern='<!-- end description -->'
          start_line=$(grep -n "$start_pattern" "${{matrix.target}}".md | cut -d ":" -f 1)
          end_line=$(grep -n "$end_pattern" "${{matrix.target}}".md | cut -d ":" -f 1)
          content=$(sed -n "$((start_line + 1)),$((end_line - 1))p" "${{matrix.target}}".md)
          result=$(echo "$content" | awk '{printf "%s<br>", $0}')
          mkdir -p outputs
          echo "$result" >> outputs/${{steps.name_action.outputs.filename}}.txt
      - uses: actions/upload-artifact@v3
        id: upload_artifact
        with:
          name: outputs
          path: outputs/*.txt
      - name: Remove files
        id: remove_files
        if: steps.upload_artifact.outcome == 'success'
        run: |
          rm -rf ./outputs/
        ####Sortir ce résultat avec un output et faire un second job avec un second pull request qui ajoute tout un par un
      - name: Create Pull Request
        if: steps.remove_files.outcome == 'success'
        uses: peter-evans/create-pull-request@v5
        with:
          title: "docs(readme): update ${{steps.name_action.outputs.filename}}.md on ${{ github.ref_name }}"
          commit-message: "docs(readme): updated ${{steps.name_action.outputs.filename}}.md inputs table"
          body: "Updated README.md inputs/outputs tables, according to ${{steps.name_action.outputs.filename}}.yml file"
          branch: update-readme--${{ github.ref_name }}--${{steps.name_action.outputs.filename}}
          delete-branch: true
          labels: bot,documentation

  set_desc:
    needs: [run-matrix]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Load outputs
        uses: actions/download-artifact@v3
        with:
          name: outputs
          path: outputs
      - name: Append Readme
        id: append_readme
        run: |
          README="./README.md"
          OUTPUTS_DIR="./outputs"
          for txt_file in "$OUTPUTS_DIR"/*.txt; do
            file_name=$(basename -- "$txt_file" .txt)
            location=$(find . -type f -name "$file_name".yml 2>/dev/null | head -n 1 | sed 's/^\.\///')
            if [ -z "$location" ]; then
              echo "Warning: $file_name.yml not found!"
            else
              description=$(cat "$txt_file")
              echo "| $file_name | $description | [$file_name](https://github.com/UlysseCarpentier/GHActions-Git-Brother/blob/main/$location)  |" >> "$README"
            fi
          done
      - name: Remove files
        id: remove_files
        if: steps.append_readme.outcome == 'success'
        run: |
          rm -rf ./outputs/
      - name: Create Pull Request
        if: steps.append_readme.outcome == 'success'
        uses: peter-evans/create-pull-request@v5
        with:
          title: "docs(readme): update README.md on ${{ github.ref_name }}"
          commit-message: "docs(readme): updated README.md Actions list table"
          body: "Updated README.md Action list tables, with the new actions files"
          branch: update-readme--${{ github.ref_name }}
          delete-branch: true
          labels: bot,documentation
          
      
