name: Readme Generator
on:
  push:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: output_matrix
        run: |
          yaml_files=$(find . -type f -name '*.yml' -print)
          echo $yaml_files
          #find . -type f -name '*.yml' -print > yaml_files.txt
          #json_array=$(echo "{ \"target\": " $(< yaml_files.txt tr -d '\r' | jq -R . | jq -s . | jq -c .) " }")
          yaml_array=$(echo "$yaml_files" | jq -R -s 'split("\n")[:-1] | map(split(" ")) | flatten')
          quoted_array=$(echo "$yaml_array" | jq -c 'map("\"" + . + "\"")')
          json_array=$(echo "{ \"target\": $quoted_array }" | tr -d '\n')
          echo $json_array
          echo "$json_array"
          #nul
          escaped_json_array=$(echo "$json_array" | sed 's/"/\\"/g')
          echo $escaped_json_array
          echo "$escaped_json_array"
          echo 'matrix="'$json_array'"' >> $GITHUB_OUTPUT
      - run: |
          echo "saleeeee  ${{steps.output_matrix.outputs.matrix}}"
          echo "saleeeeejson  ${{toJSON(steps.output_matrix.outputs.matrix)}}"
          echo "saleeeeejsontarget  ${{toJSON(steps.output_matrix.outputs.matrix).target}}"
          echo "saleeeeejsontargetfromto  ${{fromJSON(toJSON(steps.output_matrix.outputs.matrix))}}"
          echo "saleeeeejsontargetfromtotarget  ${{fromJSON(toJSON(steps.output_matrix.outputs.matrix)).target}}"

    outputs:
      actions: ${{toJSON(steps.output_matrix.outputs.matrix)}}

  run-matrix:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #target: ${{fromJSON(needs.setup.outputs.actions).target}}
       target: ${{fromJSON(needs.setup.outputs.actions).target}}
    steps:
      - run: echo "${{matrix.target}}".yml
#      - name: Run github-action-readme-generator
#        uses: bitflight-devops/github-action-readme-generator@v1.4.0
#        with:
#          action: ${{matrix.target}}.yml
#          readme: ${{matrix.target}}.md
