name: readme
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: List YAML Files
        id: list-yaml-files
        run: |
          find Python -type f -name '*.yml' -print > yaml_files.txt
          echo "::set-output name=paths::$(cat yaml_files.txt)"

      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Run github-action-readme-generator for YAML Files
        run: |
          while IFS= read -r file; do
            echo "Running workflow for file: $file"
            yaml_filename=$(basename "$file")
            echo "YAML filename: $yaml_filename"

            # Use GitHub workflow command to set the matrix dynamically.
            echo "::set-output name=matrix_yaml_file::$yaml_filename"

            # Run the github-action-readme-generator action for the current YAML file.
            uses: bitflight-devops/github-action-readme-generator@v1.4.0
            with:
              action: "./Python/$yaml_filename"
          done < yaml_files.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "docs(readme): update README.md tables on ${{ github.ref_name }}"
          commit-message: "docs(readme): updated README.md inputs table"
          body: "Updated README.md inputs/outputs tables, according to action.yml file"
          branch: update-readme--${{ github.ref_name }}
          delete-branch: false
          labels: bot,documentation
