name: Readme Generator
on:
  push:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: output_matrix
        run: |
          yaml_files=$(find . -type f -name '*.yml' -exec basename {} .yml \;)
          echo $yaml_files
          yaml_array=$(echo "$yaml_files" | jq -R -s 'split("\n")[:-1] | map(split(" ")) | flatten')
          quoted_array=$(echo "$yaml_array" | jq -c 'map("\"" + . + "\"")')
          target_string='{ "target":'
          end_string=' }'
          json_array="${target_string} ${yaml_array} ${end_string}"
          echo 'matrix='$json_array >> $GITHUB_OUTPUT
    outputs:
      actions: ${{steps.output_matrix.outputs.matrix}}

  run-matrix:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
       target: ${{fromJSON(needs.setup.outputs.actions).target}}
    steps:
      - run: |
          echo "${{matrix.target}}".yml
          echo "${{matrix.target}}".md
#      - name: Run github-action-readme-generator
#        uses: bitflight-devops/github-action-readme-generator@v1.4.0
#        with:
#          action: ${{matrix.target}}.yml
#          readme: ${{matrix.target}}.md
