name: readme
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bitflight-devops/github-action-readme-generator@v1.4.0
      - uses: magicstack/gha-commit-and-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: main
          workdir: main
          commit_message: Automatic documentation update
