name: readme
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: List YAML Files
        id: list-yaml-files
        run: |
          find Python -type f -name '*.yml' -print > yaml_files.txt
          echo "::set-output name=paths::$(cat yaml_files.txt)"

      - name: Run Workflows for YAML Files
        run: |
          for file in $(cat yaml_files.txt); do
            echo "Running workflow for file: $file"
            yaml_filename=$(basename $file)
            echo "YAML filename: $yaml_filename"

            # Create a new YAML file with the dynamically generated action input.
            echo "action: './Python/$yaml_filename'" > action_input.yml

            # Use the dynamic input file to run the github-action-readme-generator action.
            uses: bitflight-devops/github-action-readme-generator@v1.4.0
            with:
              action: ./action_input.yml
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "docs(readme): update README.md tables on ${{ github.ref_name }}"
          commit-message: "docs(readme): updated README.md inputs table"
          body: "Updated README.md inputs/outputs tables, according to action.yml file"
          branch: update-readme--${{ github.ref_name }}
          delete-branch: false
          labels: bot,documentation
