name: readme
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bitflight-devops/github-action-readme-generator@v1.4.0
        with:
          action: './Python/*.yml'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "docs(readme): update README.md tables on ${{ github.ref_name }}"
          commit-message: "docs(readme): updated README.md inputs table"
          body: "Updated README.md inputs/outputs tables, according to action.yml file"
          branch: update-readme--${{ github.ref_name }}
          delete-branch: false
          labels: bot,documentation
