name: Readme Generator
on:
  push:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: output_matrix
        run: |
          yaml_files=$(find . -type f -name '*.yml' -print)
          echo $yaml_files
          #find . -type f -name '*.yml' -print > yaml_files.txt
          #json_array=$(echo "{ \"target\": " $(< yaml_files.txt tr -d '\r' | jq -R . | jq -s . | jq -c .) " }")
          json_array=$(echo "$yaml_files" | jq -R -s 'split("\n")[:-1] | {target: .}')
          echo $json_array
          echo "matrix=\'$json_array\'" >> $GITHUB_OUTPUT
      - run: |
          echo ${{steps.output_matrix.outputs.matrix}}

    outputs:
      actions: ${{ steps.output_matrix.outputs.matrix  }}

  run-matrix:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ${{fromJSON(needs.setup.outputs.actions).target}}
    steps:
      - run: echo "${{matrix.target}}".yml
#      - name: Run github-action-readme-generator
#        uses: bitflight-devops/github-action-readme-generator@v1.4.0
#        with:
#          action: ${{matrix.target}}.yml
#          readme: ${{matrix.target}}.md
