name: Readme Generator
on:
  push:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: output_matrix
        run: |
          yaml_files=$(find . -type f -name '*.yml' -exec sh -c 'echo "$(dirname "$1")/$(basename -s .yml "$1")"' _ {} \;)
          echo $yaml_files
          yaml_array=$(echo "$yaml_files" | jq -R -s 'split("\n")[:-1] | map(split(" ")) | flatten')
          quoted_array=$(echo "$yaml_array" | jq -c 'map("\"" + . + "\"")')
          target_string='{ "target":'
          end_string=' }'
          json_array="${target_string} ${yaml_array} ${end_string}"
          echo 'matrix='$json_array >> $GITHUB_OUTPUT
    outputs:
      actions: ${{steps.output_matrix.outputs.matrix}}

  run-matrix:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
       target: ${{fromJSON(needs.setup.outputs.actions).target}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check if file exists
        id: check_file
        run: |
          if [ -e "${{ matrix.target }}".md ]; then
            echo "File exists!"
            echo "match=true" >> $GITHUB_OUTPUT
          else
            echo "File does not exist."
            echo "match=false" >> $GITHUB_OUTPUT
          fi
      - name: copy file
        if: steps.check_file.outputs.match != 'true'
        uses: canastro/copy-file-action@master
        with:
          source: "./Ressources/Base_README.md"
          target: "${{matrix.target}}".md
      - run: |
          echo "${{matrix.target}}".yml
          echo "${{matrix.target}}".md
#      - name: Run github-action-readme-generator
#        uses: bitflight-devops/github-action-readme-generator@v1.4.0
#        with:
#          action: ${{matrix.target}}.yml
#          readme: ${{matrix.target}}.md
