name: Notify Slack Action
description: Send Github Actions workflow status notifications to Slack
author: RavSam Web Solutions
on:
  workflow_call:
inputs:
  status:
    description: Job Status
    required: true
  token:
    description: Github Token for accessing workflow url
    required: false
    default: ""
  notification_title:
    description: Specify on the notification message title
    required: false
    default: "New Github Action Run"
  message_format:
    description: Specify on the notification message format
    required: false
    default: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}@{branch}> on <{commit_url}|{commit_sha}>
    \n *<{run_url}|View Run>* "
  footer:
    description: Specify the footer of the message
    required: false
    default: "<{run_url}|View Run>"
  notify_when:
    description: Specify on which events a slack notification is sent
    required: false
    default: "success,failure,cancelled,warnings,skipped"
  mention_users:
    description: Specify the slack IDs of users you want to mention
    required: false
    default: ""
  mention_users_when:
    description: Specify on which events you want to mention the users
    required: false
    default: "success,failure,cancelled,warnings,skipped"
  mention_groups:
    description: Specify the slack IDs of groups you want to mention
    required: false
    default: ""
  mention_groups_when:
    description: Specify on which events you want to mention the groups
    required: false
    default: "success,failure,cancelled,warnings,skipped"
  icon_success:
    description: Specify on icon to be used when event is success
    required: false
    default: ":heavy_check_mark:"
  icon_failure:
    description: Specify on icon to be used when event is failure
    required: false
    default: ":x:"
  icon_cancelled:
    description: Specify on icon to be used when event is cancelled
    required: false
    default: ":x:"
  icon_warnings:
    description: Specify on icon to be used when event is warnings
    required: false
    default: ":large_orange_diamond:"
  icon_skipped:
    description: Specify on icon to be used when event is skipped
    required: false
    default: ":fast_forward:"
  SLACK_WEBHOOK_URL:
    description: Specify the Slack Webhook URL to send the message to. Default to secret "ACTION_MONITORING_SLACK"
    required: true
    default: ${{ secrets.ACTION_MONITORING_SLACK }}
jobs:
  Check-Branch-Name:
    runs-on: ubuntu-latest
    steps:
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v2.3.0
        with:
          status: ${{ inputs.status }}
          token: ${{ inputs.token }}
          notification_title: ${{ inputs.notification_title }}
          message_format: ${{ inputs.message_format }}
          footer: ${{ inputs.footer }}
          notify_when: ${{ inputs.notify_when }}
          mention_users: ${{ inputs.mention_users }}
          mention_users_when: ${{ inputs.mention_users_when }}
          mention_groups: ${{ inputs.mention_groups }}
          mention_groups_when: ${{ inputs.mention_groups_when }}
          icon_success: ${{ inputs.icon_success }}
          icon_failure: ${{ inputs.icon_failure }}
          icon_cancelled: ${{ inputs.icon_cancelled }}
          icon_warnings: ${{ inputs.icon_warnings }}
          icon_skipped: ${{ inputs.icon_skipped }}
        env:
          SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}