name: SYNCRO
on:
  workflow_dispatch:
jobs:
  token_generator:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}
          permissions: >-
            {
              "contents": "write",
              "metadata": "read",
              "pull_requests": "write",
            }
      - run: "echo 'The created token is masked: ${{ steps.create_token.outputs.token }}'"
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_INSTALLATION_TOKEN: ${{ steps.create_token.outputs.token }}
          GIT_EMAIL: "ulysse.carpentier@do-now.io"
          GIT_USERNAME: "UlysseCarpentier"

#              "actions": "write",
#              "contents": "write",
#              "issues": "write",
#              "metadata": "read",
#              "pull_requests": "write",
#              "workflows": "write"
