name: SYNCRO
on:
  workflow_dispatch:
jobs:
  token_generator:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}
          permissions: >-
            {
              "actions": "write",
              "administration": "write",
              "checks": "write",
              "contents": "write",
              "deployments": "write",
              "issues": "write",
              "members": "write",
              "metadata": "read",
              "organization_administration": "write",
              "organization_hooks": "write",
              "organization_plan": "read",
              "organization_projects": "write",
              "organization_user_blocking": "write",
              "pages": "write",
              "pull_requests": "write",
              "repository_hooks": "write",
              "repository_hooks_deployments": "write",
              "repository_hooks_hooks": "write",
              "repository_hooks_pages": "write",
              "repository_hooks_pull_requests": "write",
              "secrets": "write",
              "security_events": "read",
              "single_file": "write",
              "statuses": "write",
              "team_discussions": "write",
              "vulnerability_alerts": "read",
              "workflows": "write"
            }
      - run: "echo 'The created token is masked: ${{ steps.create_token.outputs.token }}'"
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_INSTALLATION_TOKEN: ${{ steps.create_token.outputs.token }}
          GIT_EMAIL: "ulysse.carpentier@do-now.io"
          GIT_USERNAME: "UlysseCarpentier"

