name: Sync Reusable Workflows
# Git App Rights (Repo):
# Contents write
# Pull requests write
# Workflows write

# Create branch protection rule for bot-repo Pull request without review
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
jobs:
  sync_files:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}
          permissions: >-
            {
              "contents": "write",
              "metadata": "read",
              "pull_requests": "write",
              "workflows": "write"
            }
      - run: "echo 'The created token is masked: ${{ steps.create_token.outputs.token }}'"
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run GitHub File Sync
        id: sync_files
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_INSTALLATION_TOKEN: ${{ steps.create_token.outputs.token }}
          DRY_RUN: false
#Update this
          GIT_EMAIL: "ulysse.carpentier@do-now.io"
          GIT_USERNAME: "UlysseCarpentier"
#Auto merge
      - name: Enable Pull Request Automerge
        run: |
          url="${{ steps.sync_files.outputs.pull_request_urls }}"
          pr_numbers=$(echo "$url_array" | jq -r '.[] | capture("/pull/(?<number>\\d+)").number')
# Boucle sur les numéros de pull request et exécute la commande gh pr merge
          for pr_number in $pr_numbers; do
            gh pr merge --merge --auto "$pr_number"
          done
        env:
          GH_TOKEN: ${{ steps.create_token.outputs.token }}

  comment_files:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ job.status }}
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PEM }}
          permissions: >-
            {
              "contents": "write",
              "metadata": "read",
              "pull_requests": "write",
              "workflows": "write"
            }
      - run: "echo 'The created token is masked: ${{ steps.create_token.outputs.token }}'"
      - name: Checkout Repository
        id: checkout_branch
        uses: actions/checkout@v3

      - name: Comment lines
        if: steps.checkout_branch.outcome == 'success'
        id: comment_lines
        run: |
          for file in $(find . -type f -name 'R_*.yml' -path './.github/*' ); do
            echo "Commenting lines in $file"
            awk '/^name:/ { inside_block = 1; print $0 } inside_block { if (!/^on:/) print "#" $0 } /^on:/ && inside_block { inside_block = 0 } !inside_block { print $0 }' $file > temp_file && mv temp_file $file
          done
#          git config --global user.email "ulysse.carpentier@do-now.io"
#          git config --global user.name "UlysseCarpentier"
#          GIT_COMMITTER_NAME="${{ steps.create_token.outputs.token }}" git commit -a -m "Add changes"
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ steps.create_token.outputs.token }}
#          force: true
#          tags: true


      - name: Create Pull Request
        id: cpr
        if: steps.comment_lines.outcome == 'success'
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Reusable Workflows: Commenting lines"
          commit-message: "Reusable Workflows: Commenting lines"
          body: "Updated workflows files with commented lines"
          branch: repo-sync/GHActions-Git-Brother/default/${{ github.run_id }}
          base: main
          delete-branch: true
          token: ${{ steps.create_token.outputs.token }}

      - name: Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: |
          gh pr merge --merge --auto ${{ steps.cpr.outputs.pull-request-number }}
        env:
            GH_TOKEN: ${{ steps.create_token.outputs.token }}


  slack_notification:
    if: always()
    needs: sync_files
    uses: UlysseCarpentier/GHActions-Git-Brother/.github/workflows/R_Slack_Notification.yml@main
    with:
      notify_when: "failure,success"
      status: "${{ needs.sync_files.outputs.status }}"
      notification_title: "Reusable workflows sync failed"
    secrets:
      #User input
      SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
