name: Test slack setup workflow
on:
  workflow_dispatch:

jobs:
  first_job:
    name: first_job
    runs-on: ubuntu-latest
    #Important
    outputs:
      status: ${{ job.status }}
      title: ${{ steps.status_update1.outputs.title }}
    steps:
      - name: Exit Status Update1
        id: status_update1
        #User input
        run: |
          echo "title=First Title" >> $GITHUB_OUTPUT
          exit 0

  second_job:
    name: second-job
    runs-on: ubuntu-latest
    #Important
    outputs:
      status: ${{ job.status }}
      title: ${{ steps.status_update12.outputs.title }}
    steps:
      - name: Exit Status Update
        id: status_update12
        #User input
        run: |
          echo "title=Second title" >> $GITHUB_OUTPUT
          exit 1



  slack_setup:
    if: always()
    #User input
    needs: [first_job, second_job]
    uses: UlysseCarpentier/GHActions-Git-Brother/.github/workflows/R_Slack_Setup.yml@main
    with:
      jobs_status: "${{ toJSON(needs.*.outputs.status) }}"
      jobs_titles: "${{ toJSON(needs.*.outputs.title) }}"
  slack_notification:
    if: always()
    needs: slack_setup
    uses: UlysseCarpentier/GHActions-Git-Brother/.github/workflows/R_Slack_Notification.yml@main
    with:
      status: ${{needs.slack_setup.outputs.status}}
      notification_title: ${{needs.slack_setup.outputs.titles}}
      mention_users: ${{needs.slack_setup.outputs.slack_id}}
    secrets:
      #User input
      SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
